### ISSUE TITLE
Stuck on "You'll need to log into your Slack account to continue."

### ISSUE THREAD

**Issue by t1mmen** [tinyspeck/hammock#14]
Everything appears to be set up currectly. 

`/hammock/data/data_users.php` indicates I've successfully authenticated to my account and team using my "Hammock test" API application (Client ID starts with 21749...)

Yet, I can't get past the "You'll need to log into your Slack account to continue. [Authorize]" screen. 

Any pointers on how to proceed?
#### Setup:
- Hammock on #dd4f18b7822e6e064b50125458c381fcec77c32f
- PHP 5.4.4 & Apache. 
- Hammock running on http://localhost/hammock.
- API app has http://localhost/hammock as URL & oAuth URL

**Comment by kdawgwilk** [comment]
Still having issues with this and I have tried setting a different name in my hosts file and still cant get past the authorize screen

**Comment by kdawgwilk** [comment]
figured out that you cant have the http:// in front of the cookie_domain either
